# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/kitty/code/venv/lib/python2.7/site-packages/cmake/data/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Users/kitty/code/venv/lib/python2.7/site-packages/cmake/data/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/kitty/Pianorolls/midi2exp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/kitty/Pianorolls/midi2exp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Users/kitty/code/venv/lib/python2.7/site-packages/cmake/data/CMake.app/Contents/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Users/kitty/code/venv/lib/python2.7/site-packages/cmake/data/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kitty/Pianorolls/midi2exp/CMakeFiles /Users/kitty/Pianorolls/midi2exp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kitty/Pianorolls/midi2exp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named velocities

# Build rule for target.
velocities: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 velocities
.PHONY : velocities

# fast build rule for target.
velocities/fast:
	$(MAKE) -f CMakeFiles/velocities.dir/build.make CMakeFiles/velocities.dir/build
.PHONY : velocities/fast

#=============================================================================
# Target rules for targets named midi2exp

# Build rule for target.
midi2exp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 midi2exp
.PHONY : midi2exp

# fast build rule for target.
midi2exp/fast:
	$(MAKE) -f CMakeFiles/midi2exp.dir/build.make CMakeFiles/midi2exp.dir/build
.PHONY : midi2exp/fast

#=============================================================================
# Target rules for targets named expression

# Build rule for target.
expression: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 expression
.PHONY : expression

# fast build rule for target.
expression/fast:
	$(MAKE) -f CMakeFiles/expression.dir/build.make CMakeFiles/expression.dir/build
.PHONY : expression/fast

src/Expressionizer.o: src/Expressionizer.cpp.o

.PHONY : src/Expressionizer.o

# target to build an object file
src/Expressionizer.cpp.o:
	$(MAKE) -f CMakeFiles/expression.dir/build.make CMakeFiles/expression.dir/src/Expressionizer.cpp.o
.PHONY : src/Expressionizer.cpp.o

src/Expressionizer.i: src/Expressionizer.cpp.i

.PHONY : src/Expressionizer.i

# target to preprocess a source file
src/Expressionizer.cpp.i:
	$(MAKE) -f CMakeFiles/expression.dir/build.make CMakeFiles/expression.dir/src/Expressionizer.cpp.i
.PHONY : src/Expressionizer.cpp.i

src/Expressionizer.s: src/Expressionizer.cpp.s

.PHONY : src/Expressionizer.s

# target to generate assembly for a file
src/Expressionizer.cpp.s:
	$(MAKE) -f CMakeFiles/expression.dir/build.make CMakeFiles/expression.dir/src/Expressionizer.cpp.s
.PHONY : src/Expressionizer.cpp.s

src/midifile/Binasc.o: src/midifile/Binasc.cpp.o

.PHONY : src/midifile/Binasc.o

# target to build an object file
src/midifile/Binasc.cpp.o:
	$(MAKE) -f CMakeFiles/expression.dir/build.make CMakeFiles/expression.dir/src/midifile/Binasc.cpp.o
.PHONY : src/midifile/Binasc.cpp.o

src/midifile/Binasc.i: src/midifile/Binasc.cpp.i

.PHONY : src/midifile/Binasc.i

# target to preprocess a source file
src/midifile/Binasc.cpp.i:
	$(MAKE) -f CMakeFiles/expression.dir/build.make CMakeFiles/expression.dir/src/midifile/Binasc.cpp.i
.PHONY : src/midifile/Binasc.cpp.i

src/midifile/Binasc.s: src/midifile/Binasc.cpp.s

.PHONY : src/midifile/Binasc.s

# target to generate assembly for a file
src/midifile/Binasc.cpp.s:
	$(MAKE) -f CMakeFiles/expression.dir/build.make CMakeFiles/expression.dir/src/midifile/Binasc.cpp.s
.PHONY : src/midifile/Binasc.cpp.s

src/midifile/MidiEvent.o: src/midifile/MidiEvent.cpp.o

.PHONY : src/midifile/MidiEvent.o

# target to build an object file
src/midifile/MidiEvent.cpp.o:
	$(MAKE) -f CMakeFiles/expression.dir/build.make CMakeFiles/expression.dir/src/midifile/MidiEvent.cpp.o
.PHONY : src/midifile/MidiEvent.cpp.o

src/midifile/MidiEvent.i: src/midifile/MidiEvent.cpp.i

.PHONY : src/midifile/MidiEvent.i

# target to preprocess a source file
src/midifile/MidiEvent.cpp.i:
	$(MAKE) -f CMakeFiles/expression.dir/build.make CMakeFiles/expression.dir/src/midifile/MidiEvent.cpp.i
.PHONY : src/midifile/MidiEvent.cpp.i

src/midifile/MidiEvent.s: src/midifile/MidiEvent.cpp.s

.PHONY : src/midifile/MidiEvent.s

# target to generate assembly for a file
src/midifile/MidiEvent.cpp.s:
	$(MAKE) -f CMakeFiles/expression.dir/build.make CMakeFiles/expression.dir/src/midifile/MidiEvent.cpp.s
.PHONY : src/midifile/MidiEvent.cpp.s

src/midifile/MidiEventList.o: src/midifile/MidiEventList.cpp.o

.PHONY : src/midifile/MidiEventList.o

# target to build an object file
src/midifile/MidiEventList.cpp.o:
	$(MAKE) -f CMakeFiles/expression.dir/build.make CMakeFiles/expression.dir/src/midifile/MidiEventList.cpp.o
.PHONY : src/midifile/MidiEventList.cpp.o

src/midifile/MidiEventList.i: src/midifile/MidiEventList.cpp.i

.PHONY : src/midifile/MidiEventList.i

# target to preprocess a source file
src/midifile/MidiEventList.cpp.i:
	$(MAKE) -f CMakeFiles/expression.dir/build.make CMakeFiles/expression.dir/src/midifile/MidiEventList.cpp.i
.PHONY : src/midifile/MidiEventList.cpp.i

src/midifile/MidiEventList.s: src/midifile/MidiEventList.cpp.s

.PHONY : src/midifile/MidiEventList.s

# target to generate assembly for a file
src/midifile/MidiEventList.cpp.s:
	$(MAKE) -f CMakeFiles/expression.dir/build.make CMakeFiles/expression.dir/src/midifile/MidiEventList.cpp.s
.PHONY : src/midifile/MidiEventList.cpp.s

src/midifile/MidiFile.o: src/midifile/MidiFile.cpp.o

.PHONY : src/midifile/MidiFile.o

# target to build an object file
src/midifile/MidiFile.cpp.o:
	$(MAKE) -f CMakeFiles/expression.dir/build.make CMakeFiles/expression.dir/src/midifile/MidiFile.cpp.o
.PHONY : src/midifile/MidiFile.cpp.o

src/midifile/MidiFile.i: src/midifile/MidiFile.cpp.i

.PHONY : src/midifile/MidiFile.i

# target to preprocess a source file
src/midifile/MidiFile.cpp.i:
	$(MAKE) -f CMakeFiles/expression.dir/build.make CMakeFiles/expression.dir/src/midifile/MidiFile.cpp.i
.PHONY : src/midifile/MidiFile.cpp.i

src/midifile/MidiFile.s: src/midifile/MidiFile.cpp.s

.PHONY : src/midifile/MidiFile.s

# target to generate assembly for a file
src/midifile/MidiFile.cpp.s:
	$(MAKE) -f CMakeFiles/expression.dir/build.make CMakeFiles/expression.dir/src/midifile/MidiFile.cpp.s
.PHONY : src/midifile/MidiFile.cpp.s

src/midifile/MidiMessage.o: src/midifile/MidiMessage.cpp.o

.PHONY : src/midifile/MidiMessage.o

# target to build an object file
src/midifile/MidiMessage.cpp.o:
	$(MAKE) -f CMakeFiles/expression.dir/build.make CMakeFiles/expression.dir/src/midifile/MidiMessage.cpp.o
.PHONY : src/midifile/MidiMessage.cpp.o

src/midifile/MidiMessage.i: src/midifile/MidiMessage.cpp.i

.PHONY : src/midifile/MidiMessage.i

# target to preprocess a source file
src/midifile/MidiMessage.cpp.i:
	$(MAKE) -f CMakeFiles/expression.dir/build.make CMakeFiles/expression.dir/src/midifile/MidiMessage.cpp.i
.PHONY : src/midifile/MidiMessage.cpp.i

src/midifile/MidiMessage.s: src/midifile/MidiMessage.cpp.s

.PHONY : src/midifile/MidiMessage.s

# target to generate assembly for a file
src/midifile/MidiMessage.cpp.s:
	$(MAKE) -f CMakeFiles/expression.dir/build.make CMakeFiles/expression.dir/src/midifile/MidiMessage.cpp.s
.PHONY : src/midifile/MidiMessage.cpp.s

src/midifile/Options.o: src/midifile/Options.cpp.o

.PHONY : src/midifile/Options.o

# target to build an object file
src/midifile/Options.cpp.o:
	$(MAKE) -f CMakeFiles/expression.dir/build.make CMakeFiles/expression.dir/src/midifile/Options.cpp.o
.PHONY : src/midifile/Options.cpp.o

src/midifile/Options.i: src/midifile/Options.cpp.i

.PHONY : src/midifile/Options.i

# target to preprocess a source file
src/midifile/Options.cpp.i:
	$(MAKE) -f CMakeFiles/expression.dir/build.make CMakeFiles/expression.dir/src/midifile/Options.cpp.i
.PHONY : src/midifile/Options.cpp.i

src/midifile/Options.s: src/midifile/Options.cpp.s

.PHONY : src/midifile/Options.s

# target to generate assembly for a file
src/midifile/Options.cpp.s:
	$(MAKE) -f CMakeFiles/expression.dir/build.make CMakeFiles/expression.dir/src/midifile/Options.cpp.s
.PHONY : src/midifile/Options.cpp.s

tools/midi2exp.o: tools/midi2exp.cpp.o

.PHONY : tools/midi2exp.o

# target to build an object file
tools/midi2exp.cpp.o:
	$(MAKE) -f CMakeFiles/midi2exp.dir/build.make CMakeFiles/midi2exp.dir/tools/midi2exp.cpp.o
.PHONY : tools/midi2exp.cpp.o

tools/midi2exp.i: tools/midi2exp.cpp.i

.PHONY : tools/midi2exp.i

# target to preprocess a source file
tools/midi2exp.cpp.i:
	$(MAKE) -f CMakeFiles/midi2exp.dir/build.make CMakeFiles/midi2exp.dir/tools/midi2exp.cpp.i
.PHONY : tools/midi2exp.cpp.i

tools/midi2exp.s: tools/midi2exp.cpp.s

.PHONY : tools/midi2exp.s

# target to generate assembly for a file
tools/midi2exp.cpp.s:
	$(MAKE) -f CMakeFiles/midi2exp.dir/build.make CMakeFiles/midi2exp.dir/tools/midi2exp.cpp.s
.PHONY : tools/midi2exp.cpp.s

tools/velocities.o: tools/velocities.cpp.o

.PHONY : tools/velocities.o

# target to build an object file
tools/velocities.cpp.o:
	$(MAKE) -f CMakeFiles/velocities.dir/build.make CMakeFiles/velocities.dir/tools/velocities.cpp.o
.PHONY : tools/velocities.cpp.o

tools/velocities.i: tools/velocities.cpp.i

.PHONY : tools/velocities.i

# target to preprocess a source file
tools/velocities.cpp.i:
	$(MAKE) -f CMakeFiles/velocities.dir/build.make CMakeFiles/velocities.dir/tools/velocities.cpp.i
.PHONY : tools/velocities.cpp.i

tools/velocities.s: tools/velocities.cpp.s

.PHONY : tools/velocities.s

# target to generate assembly for a file
tools/velocities.cpp.s:
	$(MAKE) -f CMakeFiles/velocities.dir/build.make CMakeFiles/velocities.dir/tools/velocities.cpp.s
.PHONY : tools/velocities.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... velocities"
	@echo "... midi2exp"
	@echo "... expression"
	@echo "... src/Expressionizer.o"
	@echo "... src/Expressionizer.i"
	@echo "... src/Expressionizer.s"
	@echo "... src/midifile/Binasc.o"
	@echo "... src/midifile/Binasc.i"
	@echo "... src/midifile/Binasc.s"
	@echo "... src/midifile/MidiEvent.o"
	@echo "... src/midifile/MidiEvent.i"
	@echo "... src/midifile/MidiEvent.s"
	@echo "... src/midifile/MidiEventList.o"
	@echo "... src/midifile/MidiEventList.i"
	@echo "... src/midifile/MidiEventList.s"
	@echo "... src/midifile/MidiFile.o"
	@echo "... src/midifile/MidiFile.i"
	@echo "... src/midifile/MidiFile.s"
	@echo "... src/midifile/MidiMessage.o"
	@echo "... src/midifile/MidiMessage.i"
	@echo "... src/midifile/MidiMessage.s"
	@echo "... src/midifile/Options.o"
	@echo "... src/midifile/Options.i"
	@echo "... src/midifile/Options.s"
	@echo "... tools/midi2exp.o"
	@echo "... tools/midi2exp.i"
	@echo "... tools/midi2exp.s"
	@echo "... tools/velocities.o"
	@echo "... tools/velocities.i"
	@echo "... tools/velocities.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

